# Kubernetes Manifest file - Deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: php-deployment
spec:
  selector:
    matchLabels:
      app: whalephp
  replicas: 3
  template:
    metadata:
      labels:
        app: whalephp
    spec:
      containers:
      - name: whalephp
        image: ${{ secrets.REGISTRY_NAME }}.azurecr.io/testimage:${{ github.sha }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
